name: Check

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun
      - run: bun install
        name: Install Dependencies
      - run: bun run lint
        name: Lint
      - run: bun run check
        name: Type Check
      - run: bun run build
        name: Build
